GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdDIiLCJpYXQiOjE2NjAwNjI5Nzd9.a1bdCWx_zsgj2DxFrIsIuFdmQ3XhtygPI3B2pQh0Qm4

###
POST http://localhost:3000/login
Content-Type: application/json
  
  {
    "username": "test2"
  }